### ISSUE TITLE
Caractère `/` manquant ?

### ISSUE THREAD

**Issue by pierrepo** [benoistlaurent/unix_tutorial#6]
Dans la rubrique *Manipulating files and directories*, *Where am I?*, est-ce que : 

> `home/benoist/list.txt` is a file located in `/home/benoist`.

ne devrait pas être 

> `/home/benoist/list.txt` is a file located in `/home/benoist`.

?

**Comment by benoistlaurent** [comment]
fixed in 30d75d4
